name: Build binary
on: [push]

jobs:
  build-aarch64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pguyot/arm-runner-action@v2
        id: build_image
        with:
          cpu: cortex-a53
          base_image: raspios_lite_arm64:2022-01-28
          image_additional_mb: 1024
          commands:
            sudo apt-get install -y build-essential libudev-dev, autoconf, pkg-config, patchelf
            ./build.sh
