name: Build binary
on: [push]

jobs:
  build-aarch64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pguyot/arm-runner-action@v2
        id: build_image
        with:
          cpu: cortex-a53
          base_image: raspios_lite_arm64:2023-05-03
          image_additional_mb: 1024
          commands: |
            ls -al
            sudo apt-get update
            sudo apt-get install -y build-essential libudev-dev autoconf pkg-config patchelf
            chmod +x ./build.sh
            ./build.sh
      - uses: actions/upload-artifact@v4
        with:
          retention-days: 90
          name: linux-aarch64
          path: tool-dfuutil-0.11-*-aarch64.tar.gz
